# .streamlit/secrets.toml (CLEANED)

ALPHAVANTAGE_API_KEY = "F6DEPCVL8IU9ZKAO"
GEMINI_API_KEY = "AIzaSyCW-sKyNFFkWz4hiysMWJR6Fyj342-GhkY"
OPENAQ_API_KEY = "0e673c3f15e1c0733ac022d51e0966fc3e721fc35b52e42082e18815ae49084f"
WAQI_TOKEN = "efc26bc8e169b40bb7d85dba79e0b96aaf84229a"
NEWSAPI_KEY = "pub_a3c1025e77b84894b2cd7c545677906d"
